#!/usr/bin/env python3
"""
test_landing_serve.py — end-to-end test for the landing/serve.py wrapper.

Starts the HTTP server on an ephemeral port, hits GET / and POST /api/tag
with a real STL generated by the test itself, then:
  - asserts the response includes a valid manifest
  - asserts the L1 watermark in the returned gcode decodes back to the
    printer_id + job_seq + ts we sent
  - asserts the L2 watermark in the returned STL diffs back to the
    order_id we sent
  - asserts a wrong order_id fails the verify

Pure stdlib (no requests, no pytest-flask). ~5 s on a warm venv.
"""
from __future__ import annotations

import base64
import io
import json
import socket
import struct
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SERVE = REPO / "landing" / "serve.py"


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _make_binary_stl(size_mm: float = 30.0) -> bytes:
    """Generate a tiny binary STL for upload. ~24 KB."""
    import numpy as np
    import stl

    mesh = stl.mesh.Mesh(np.zeros(12, dtype=stl.mesh.Mesh.dtype))
    h = size_mm / 2.0
    # 12 triangles of a cube
    data = np.array(
        [
            # +Z
            [[-h, -h, h], [h, -h, h], [h, h, h]],
            [[-h, -h, h], [h, h, h], [-h, h, h]],
            # -Z
            [[-h, -h, -h], [h, h, -h], [h, -h, -h]],
            [[-h, -h, -h], [-h, h, -h], [h, h, -h]],
            # +X
            [[h, -h, -h], [h, h, -h], [h, h, h]],
            [[h, -h, -h], [h, h, h], [h, -h, h]],
            # -X
            [[-h, -h, -h], [-h, h, h], [-h, h, -h]],
            [[-h, -h, -h], [-h, -h, h], [-h, h, h]],
            # +Y
            [[-h, h, -h], [h, h, -h], [h, h, h]],
            [[-h, h, -h], [h, h, h], [-h, h, h]],
            # -Y
            [[-h, -h, -h], [h, -h, h], [h, -h, -h]],
            [[-h, -h, -h], [-h, -h, h], [h, -h, h]],
        ],
        dtype=np.float32,
    )
    mesh.vectors = data
    buf = io.BytesIO()
    mesh.save("cube", buf)
    return buf.getvalue()


@pytest.fixture(scope="module")
def server():
    port = _free_port()
    env = dict(__import__("os").environ, PATH=__import__("os").environ["PATH"])
    proc = subprocess.Popen(
        [sys.executable, str(SERVE), "--host", "127.0.0.1", "--port", str(port)],
        cwd=str(REPO),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    # Wait for /health to come up
    import urllib.request
    deadline = time.time() + 15
    base = f"http://127.0.0.1:{port}"
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{base}/health", timeout=1) as r:
                if r.status == 200:
                    break
        except Exception:
            time.sleep(0.2)
    else:
        proc.terminate()
        out, err = proc.communicate(timeout=5)
        pytest.fail(f"serve.py did not come up in 15 s. stderr:\n{err.decode()}")
    yield base
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


def test_landing_html_served(server):
    import urllib.request
    with urllib.request.urlopen(f"{server}/", timeout=5) as r:
        assert r.status == 200
        body = r.read().decode()
    assert "theapk · ghostprint" in body
    assert "/api/tag" in body
    assert "ORDER-2026-0001" in body  # placeholder


def test_tag_e2e_round_trip(server):
    """Upload STL, get tagged STL + gcode back, verify L1 + L2 round-trip."""
    import urllib.request
    import urllib.error

    stl_bytes = _make_binary_stl()
    order_id = "ORDER-TEST-LANDING-001"
    printer = "bambucco-1"
    job_seq = 99

    # multipart/form-data via stdlib
    boundary = "----gp-test-boundary-x7y9z"
    parts: list[bytes] = []
    def add_field(name: str, value: str):
        parts.append(f"--{boundary}\r\n".encode())
        parts.append(f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode())
        parts.append(value.encode())
        parts.append(b"\r\n")
    add_field("order_id", order_id)
    add_field("printer", printer)
    add_field("job_seq", str(job_seq))
    parts.append(f"--{boundary}\r\n".encode())
    parts.append(
        b'Content-Disposition: form-data; name="stl"; filename="cube.stl"\r\n'
        b"Content-Type: application/octet-stream\r\n\r\n"
    )
    parts.append(stl_bytes)
    parts.append(b"\r\n")
    parts.append(f"--{boundary}--\r\n".encode())
    body = b"".join(parts)

    req = urllib.request.Request(
        f"{server}/api/tag",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        assert r.status == 200
        resp = json.loads(r.read())

    # Manifest sanity
    assert resp["manifest"]["order_id"] == order_id
    assert resp["manifest"]["printer_id"]
    assert resp["manifest"]["master_stl_sha256"]
    assert resp["manifest"]["tagged_stl_sha256"]
    assert resp["size_stl"] > 0
    assert resp["size_gcode"] > 0
    assert resp["tagged_stl_b64"]
    assert resp["tagged_gcode_b64"]

    # Decode gcode → L1 round trip
    gcode = base64.b64decode(resp["tagged_gcode_b64"]).decode()
    sys.path.insert(0, str(REPO / "src"))
    from ghostprint_core import l1_extract_from_gcode, l2_verify_match

    l1 = l1_extract_from_gcode(gcode)
    assert l1["printer_id"] == resp["manifest"]["printer_id"], (
        f"L1 printer_id mismatch: {l1['printer_id']} vs {resp['manifest']['printer_id']}"
    )
    assert l1["job_seq"] == job_seq, f"L1 job_seq mismatch: {l1['job_seq']} vs {job_seq}"

    # L2 round trip — diff tagged STL against the master we sent
    tagged_path = Path(tempfile.mkdtemp()) / "tagged.stl"
    tagged_path.write_bytes(base64.b64decode(resp["tagged_stl_b64"]))
    master_path = Path(tempfile.mkdtemp()) / "master.stl"
    master_path.write_bytes(stl_bytes)

    import stl

    tagged = stl.mesh.Mesh.from_file(str(tagged_path))
    master = stl.mesh.Mesh.from_file(str(master_path))
    assert l2_verify_match(tagged, master, order_id) is True, "L2 verify should pass for correct order_id"
    assert l2_verify_match(tagged, master, "ORDER-WRONG-XYZ") is False, "L2 verify should fail for wrong order_id"


def test_tag_rejects_non_stl(server):
    import urllib.request
    boundary = "----gp-test-boundary-x7y9z"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="order_id"\r\n\r\nX\r\n'
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="printer"\r\n\r\np\r\n'
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="job_seq"\r\n\r\n1\r\n'
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="stl"; filename="x.stl"\r\n'
        f"Content-Type: text/plain\r\n\r\n"
        f"this is plain text not an stl"
        f"\r\n--{boundary}--\r\n"
    ).encode()
    req = urllib.request.Request(
        f"{server}/api/tag",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )
    try:
        urllib.request.urlopen(req, timeout=5)
        pytest.fail("expected 400 for non-STL upload")
    except urllib.error.HTTPError as e:
        assert e.code == 400
        body = json.loads(e.read())
        assert "STL" in body["error"]
